### ISSUE TITLE
Menu - should the Lab41 logo stay with the user as he/she scrolls (similar to the menu)?

### ISSUE THREAD

**Issue by kelaine** [BraveUX/lab41#1]

**Comment by sarahkleins** [comment]
Should also change color, like menu

**Comment by jaxgeller** [comment]
Seems like offset range is not large enough 
![image](https://cloud.githubusercontent.com/assets/4494509/9366940/3f6954f2-4688-11e5-8147-9cb27a3f6224.png)

**Comment by jaxgeller** [comment]
same as #58
