### ISSUE TITLE
Work - hero area text containers

### ISSUE THREAD

**Issue by kelaine** [BraveUX/lab41#10]
![screen shot 2015-08-14 at 12 22 31 pm](https://cloud.githubusercontent.com/assets/9937697/9278531/66428704-427f-11e5-9146-2f1e03ced7b4.png)

**Comment by sarahkleins** [comment]
Links are red on mobile, for consistency's sake assumed they should be red on desktop as well? @theastralj

**Comment by sarahkleins** [comment]
Spoke with Jordan, set max with on heading and detail (all pages) for consistency
