### ISSUE TITLE
Process - hero - text container

### ISSUE THREAD

**Issue by kelaine** [BraveUX/lab41#28]
@theastralj Even in the mockup, it feels pretty wide.
![screen shot 2015-08-14 at 1 41 19 pm](https://cloud.githubusercontent.com/assets/9937697/9280143/50f92b54-428a-11e5-8be6-853ebc9587ac.png)

**Comment by sarahkleins** [comment]
Talked with @theastralj, gave each intro heading and detail a max-width.
