### ISSUE TITLE
Home - Gab41 section - button and CTA should be aligned

### ISSUE THREAD

**Issue by kelaine** [BraveUX/lab41#64]
![screen shot 2015-09-02 at 10 17 01 am](https://cloud.githubusercontent.com/assets/9937697/9633676/121b04e4-515c-11e5-9c75-2e4953153de5.png)

**Comment by jaxgeller** [comment]
@kelaine this unfortunately wont be possible just because the excerpt (the content on the right) is editable by them and varies by length. It could 20 lines or 5, you never know.
